[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd"))']
# Mold is a very fast custom linker. Check out https://github.com/rui314/mold.git
# Mold only supports ELF binaries, so this is only enabled for Linux and BSD targets.
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
