[package]
name = "amber-diagnostic"
description.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
amber-source = { workspace = true }

thiserror = { workspace = true }

typed-builder = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
